### ISSUE TITLE
Could I have clarification on this issue

### ISSUE THREAD

**Issue by walterjamesperry** [xiov91/thats-my-opinion#12]
Is it possible to delete a user account?
When an anonymous user posts a comment and they decide to delete their account, will the deletion of deleted comments cascade through out the site?

**Comment by xiov91** [comment]
The original idea was to make it possible for people to comment anonymously but still require users to be logged in to make actual posts. But due to time restraints and just being unsure of how far we can really get, we decided to put that feature on the backburner for now and just focus on the main, basic functionality.

Ideally, the idea would have been to make temporary "accounts" for anonymous sessions, so they wouldn't be able to delete them and the comments wouldn't be deletable, I think. But beyond the initial idea and realizing how complex it is vs. what we can do right now, I don't think any of us put more thought into it than that.
